CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    display_name VARCHAR(50) NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(16) NOT NULL CHECK (role IN ('admin', 'user')),
    employee_number VARCHAR(30),
    approval_status VARCHAR(16) NOT NULL DEFAULT 'approved'
        CHECK (approval_status IN ('pending', 'approved', 'rejected')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    last_login_at TIMESTAMPTZ,
    signup_requested_at TIMESTAMPTZ,
    decision_at TIMESTAMPTZ,
    decision_by VARCHAR(32),
    rejection_reason VARCHAR(500)
);

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS employee_number VARCHAR(30);

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS approval_status VARCHAR(16) NOT NULL DEFAULT 'approved';

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS signup_requested_at TIMESTAMPTZ;

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS decision_at TIMESTAMPTZ;

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS decision_by VARCHAR(32);

ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(500);

CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_employee_number
ON app_users(employee_number);

CREATE TABLE IF NOT EXISTS auth_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_username VARCHAR(32) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_username VARCHAR(32) NOT NULL DEFAULT '',
    detail TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_created_at
ON auth_audit_log(created_at DESC);
