from __future__ import annotations

import base64
import hashlib
import hmac
import os
import re
import sqlite3
import threading
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Mapping

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # PostgreSQL is optional for local SQLite-only development.
    psycopg = None
    dict_row = None


PBKDF2_ALGORITHM = "sha256"
PBKDF2_ITERATIONS = 600_000
PASSWORD_SCHEME = "pbkdf2_sha256"
MAX_FAILED_ATTEMPTS = 5
LOCK_MINUTES = 15
USERNAME_PATTERN = re.compile(r"^[a-z0-9._-]{3,32}$")
VALID_ROLES = {"admin", "user"}
VALID_APPROVAL_STATUSES = {"pending", "approved", "rejected"}
EMPLOYEE_NUMBER_PATTERN = re.compile(r"^[A-Za-z0-9_-]{2,30}$")


class AuthError(ValueError):
    """Raised when an account operation cannot be completed safely."""


class PasswordPolicyError(AuthError):
    """Raised when a password does not meet the local password policy."""


class AuthConfigurationError(AuthError):
    """Raised when the configured authentication database is unavailable."""


@dataclass(frozen=True)
class AuthUser:
    id: int
    username: str
    display_name: str
    role: str
    employee_number: str | None
    approval_status: str
    is_active: bool
    must_change_password: bool
    failed_attempts: int
    locked_until: datetime | None
    created_at: datetime
    updated_at: datetime
    last_login_at: datetime | None
    signup_requested_at: datetime | None
    decision_at: datetime | None
    decision_by: str | None
    rejection_reason: str | None

    @property
    def is_admin(self) -> bool:
        return self.role == "admin"

    @property
    def is_approved(self) -> bool:
        return self.approval_status == "approved"


@dataclass(frozen=True)
class AuthenticationResult:
    user: AuthUser | None
    status: str
    rejection_reason: str | None = None


@dataclass(frozen=True)
class AuditEvent:
    id: int
    actor_username: str
    action: str
    target_username: str
    detail: str
    created_at: datetime


@dataclass(frozen=True)
class MigrationResult:
    users: int
    audit_events: int


SQLITE_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS app_users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT NOT NULL COLLATE NOCASE UNIQUE,
        display_name TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
        employee_number TEXT COLLATE NOCASE,
        approval_status TEXT NOT NULL DEFAULT 'approved'
            CHECK (approval_status IN ('pending', 'approved', 'rejected')),
        is_active INTEGER NOT NULL DEFAULT 1,
        must_change_password INTEGER NOT NULL DEFAULT 1,
        failed_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_login_at TEXT,
        signup_requested_at TEXT,
        decision_at TEXT,
        decision_by TEXT,
        rejection_reason TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auth_audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        actor_username TEXT NOT NULL,
        action TEXT NOT NULL,
        target_username TEXT NOT NULL DEFAULT '',
        detail TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_auth_audit_created_at
    ON auth_audit_log(created_at DESC)
    """,
)


POSTGRES_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS app_users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(32) NOT NULL UNIQUE,
        display_name VARCHAR(50) NOT NULL,
        password_hash TEXT NOT NULL,
        role VARCHAR(16) NOT NULL CHECK (role IN ('admin', 'user')),
        employee_number VARCHAR(30),
        approval_status VARCHAR(16) NOT NULL DEFAULT 'approved'
            CHECK (approval_status IN ('pending', 'approved', 'rejected')),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
        failed_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL,
        updated_at TIMESTAMPTZ NOT NULL,
        last_login_at TIMESTAMPTZ,
        signup_requested_at TIMESTAMPTZ,
        decision_at TIMESTAMPTZ,
        decision_by VARCHAR(32),
        rejection_reason VARCHAR(500)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auth_audit_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_username VARCHAR(32) NOT NULL,
        action VARCHAR(64) NOT NULL,
        target_username VARCHAR(32) NOT NULL DEFAULT '',
        detail TEXT NOT NULL DEFAULT '',
        created_at TIMESTAMPTZ NOT NULL
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_auth_audit_created_at
    ON auth_audit_log(created_at DESC)
    """,
)


class _ConnectionAdapter:
    def __init__(self, raw_connection: Any, backend_name: str) -> None:
        self.raw_connection = raw_connection
        self.backend_name = backend_name

    def _adapt_sql(self, sql: str) -> str:
        if self.backend_name == "postgresql":
            return sql.replace("?", "%s")
        return sql

    def execute(self, sql: str, params: tuple[Any, ...] = ()) -> Any:
        return self.raw_connection.execute(self._adapt_sql(sql), params)

    def __enter__(self) -> _ConnectionAdapter:
        return self

    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool:
        try:
            if exc_type is None:
                self.raw_connection.commit()
            else:
                self.raw_connection.rollback()
        finally:
            self.raw_connection.close()
        return False


def normalize_username(username: str) -> str:
    normalized = str(username or "").strip().casefold()
    if not USERNAME_PATTERN.fullmatch(normalized):
        raise AuthError("아이디는 영문 소문자·숫자·마침표·밑줄·하이픈 3~32자로 입력하세요.")
    return normalized


def validate_display_name(display_name: str) -> str:
    normalized = " ".join(str(display_name or "").split())
    if not 1 <= len(normalized) <= 50:
        raise AuthError("표시 이름은 1~50자로 입력하세요.")
    return normalized


def normalize_employee_number(employee_number: str) -> str:
    normalized = str(employee_number or "").strip().upper()
    if not EMPLOYEE_NUMBER_PATTERN.fullmatch(normalized):
        raise AuthError("사번은 영문자·숫자·밑줄·하이픈 2~30자로 입력하세요.")
    return normalized


def validate_password(password: str) -> None:
    value = str(password or "")
    if len(value) < 10:
        raise PasswordPolicyError("비밀번호는 10자 이상이어야 합니다.")
    if len(value) > 128:
        raise PasswordPolicyError("비밀번호는 128자 이하여야 합니다.")
    if not re.search(r"[A-Za-z]", value) or not re.search(r"\d", value):
        raise PasswordPolicyError("비밀번호에는 영문자와 숫자를 각각 하나 이상 포함하세요.")


def hash_password(password: str, *, iterations: int = PBKDF2_ITERATIONS) -> str:
    validate_password(password)
    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac(
        PBKDF2_ALGORITHM,
        password.encode("utf-8"),
        salt,
        iterations,
    )
    return "$".join(
        (
            PASSWORD_SCHEME,
            str(iterations),
            base64.urlsafe_b64encode(salt).decode("ascii"),
            base64.urlsafe_b64encode(digest).decode("ascii"),
        )
    )


def verify_password(password: str, encoded: str) -> bool:
    try:
        scheme, raw_iterations, raw_salt, raw_digest = encoded.split("$", 3)
        if scheme != PASSWORD_SCHEME:
            return False
        iterations = int(raw_iterations)
        salt = base64.urlsafe_b64decode(raw_salt.encode("ascii"))
        expected = base64.urlsafe_b64decode(raw_digest.encode("ascii"))
    except (ValueError, TypeError):
        return False
    actual = hashlib.pbkdf2_hmac(
        PBKDF2_ALGORITHM,
        str(password or "").encode("utf-8"),
        salt,
        iterations,
    )
    return hmac.compare_digest(actual, expected)


class AuthStore:
    def __init__(
        self,
        path: Path | str | None = None,
        *,
        database_url: str | None = None,
    ) -> None:
        project_root = Path(__file__).resolve().parents[1]
        configured_url = str(database_url or "").strip()
        if configured_url.startswith("postgres://"):
            configured_url = "postgresql://" + configured_url[len("postgres://") :]
        if configured_url and not configured_url.startswith("postgresql://"):
            raise AuthConfigurationError(
                "AUTH_DATABASE_URL은 postgresql:// 형식이어야 합니다."
            )
        self.database_url = configured_url or None
        self.backend_name = "postgresql" if self.database_url else "sqlite"
        self.path = (
            None
            if self.database_url
            else Path(path) if path is not None else project_root / "data" / "auth.db"
        )
        if self.path is not None:
            self.path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.RLock()
        self._initialize()

    @property
    def storage_label(self) -> str:
        return "PostgreSQL" if self.backend_name == "postgresql" else "로컬 SQLite"

    def _connect(self) -> _ConnectionAdapter:
        if self.backend_name == "postgresql":
            if psycopg is None or dict_row is None:
                raise AuthConfigurationError(
                    "PostgreSQL 사용에 필요한 psycopg 패키지가 설치되지 않았습니다."
                )
            try:
                connection = psycopg.connect(
                    self.database_url,
                    row_factory=dict_row,
                    connect_timeout=10,
                    application_name="nxt_dashboard_auth",
                )
            except Exception as exc:
                raise AuthConfigurationError(
                    "PostgreSQL 인증 DB에 연결하지 못했습니다. "
                    "접속주소·계정·SSL 및 네트워크 허용 설정을 확인하세요."
                ) from exc
            return _ConnectionAdapter(connection, self.backend_name)
        if self.path is None:
            raise AuthConfigurationError("SQLite 인증 DB 경로가 설정되지 않았습니다.")
        connection = sqlite3.connect(self.path, timeout=30)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA busy_timeout = 30000")
        return _ConnectionAdapter(connection, self.backend_name)

    def _initialize(self) -> None:
        with self._lock, self._connect() as connection:
            if self.backend_name == "sqlite":
                connection.execute("PRAGMA journal_mode = WAL")
                connection.execute("PRAGMA synchronous = NORMAL")
                schema_statements = SQLITE_SCHEMA_STATEMENTS
            else:
                schema_statements = POSTGRES_SCHEMA_STATEMENTS
            for statement in schema_statements:
                connection.execute(statement)
            self._ensure_signup_columns(connection)

    def _ensure_signup_columns(self, connection: _ConnectionAdapter) -> None:
        """Add registration fields without invalidating previously issued accounts."""
        if self.backend_name == "sqlite":
            existing_columns = {
                str(row["name"])
                for row in connection.execute("PRAGMA table_info(app_users)").fetchall()
            }
            sqlite_additions = {
                "employee_number": "employee_number TEXT COLLATE NOCASE",
                "approval_status": (
                    "approval_status TEXT NOT NULL DEFAULT 'approved'"
                ),
                "signup_requested_at": "signup_requested_at TEXT",
                "decision_at": "decision_at TEXT",
                "decision_by": "decision_by TEXT",
                "rejection_reason": "rejection_reason TEXT",
            }
            for column_name, definition in sqlite_additions.items():
                if column_name not in existing_columns:
                    connection.execute(
                        f"ALTER TABLE app_users ADD COLUMN {definition}"
                    )
        else:
            postgres_additions = (
                "ADD COLUMN IF NOT EXISTS employee_number VARCHAR(30)",
                (
                    "ADD COLUMN IF NOT EXISTS approval_status VARCHAR(16) "
                    "NOT NULL DEFAULT 'approved'"
                ),
                "ADD COLUMN IF NOT EXISTS signup_requested_at TIMESTAMPTZ",
                "ADD COLUMN IF NOT EXISTS decision_at TIMESTAMPTZ",
                "ADD COLUMN IF NOT EXISTS decision_by VARCHAR(32)",
                "ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(500)",
            )
            for addition in postgres_additions:
                connection.execute(f"ALTER TABLE app_users {addition}")
        connection.execute(
            """
            UPDATE app_users
            SET approval_status = 'approved'
            WHERE approval_status IS NULL OR approval_status = ''
            """
        )
        connection.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_employee_number
            ON app_users(employee_number)
            """
        )

    @staticmethod
    def _now() -> datetime:
        return datetime.now(timezone.utc)

    @staticmethod
    def _serialize_time(value: datetime) -> str:
        return value.astimezone(timezone.utc).isoformat(timespec="seconds")

    @staticmethod
    def _parse_time(value: datetime | str | None) -> datetime | None:
        if not value:
            return None
        if isinstance(value, datetime):
            return value
        return datetime.fromisoformat(value)

    @staticmethod
    def _is_unique_violation(exc: Exception) -> bool:
        return isinstance(exc, sqlite3.IntegrityError) or getattr(
            exc, "sqlstate", None
        ) == "23505"

    @classmethod
    def _user_from_row(cls, row: Mapping[str, Any]) -> AuthUser:
        return AuthUser(
            id=int(row["id"]),
            username=str(row["username"]),
            display_name=str(row["display_name"]),
            role=str(row["role"]),
            employee_number=(
                str(row["employee_number"]) if row["employee_number"] else None
            ),
            approval_status=str(row["approval_status"] or "approved"),
            is_active=bool(row["is_active"]),
            must_change_password=bool(row["must_change_password"]),
            failed_attempts=int(row["failed_attempts"]),
            locked_until=cls._parse_time(row["locked_until"]),
            created_at=cls._parse_time(row["created_at"]) or cls._now(),
            updated_at=cls._parse_time(row["updated_at"]) or cls._now(),
            last_login_at=cls._parse_time(row["last_login_at"]),
            signup_requested_at=cls._parse_time(row["signup_requested_at"]),
            decision_at=cls._parse_time(row["decision_at"]),
            decision_by=(str(row["decision_by"]) if row["decision_by"] else None),
            rejection_reason=(
                str(row["rejection_reason"]) if row["rejection_reason"] else None
            ),
        )

    @classmethod
    def _audit_from_row(cls, row: Mapping[str, Any]) -> AuditEvent:
        return AuditEvent(
            id=int(row["id"]),
            actor_username=str(row["actor_username"]),
            action=str(row["action"]),
            target_username=str(row["target_username"]),
            detail=str(row["detail"]),
            created_at=cls._parse_time(row["created_at"]) or cls._now(),
        )

    def _write_audit(
        self,
        connection: _ConnectionAdapter,
        *,
        actor_username: str,
        action: str,
        target_username: str = "",
        detail: str = "",
    ) -> None:
        connection.execute(
            """
            INSERT INTO auth_audit_log (
                actor_username, action, target_username, detail, created_at
            ) VALUES (?, ?, ?, ?, ?)
            """,
            (
                actor_username,
                action,
                target_username,
                detail,
                self._serialize_time(self._now()),
            ),
        )

    @staticmethod
    def _require_admin(
        connection: _ConnectionAdapter,
        actor_user_id: int,
    ) -> Mapping[str, Any]:
        actor = connection.execute(
            "SELECT * FROM app_users WHERE id = ?",
            (int(actor_user_id),),
        ).fetchone()
        if (
            actor is None
            or not bool(actor["is_active"])
            or actor["role"] != "admin"
            or str(actor["approval_status"]) != "approved"
        ):
            raise AuthError("관리자 권한이 필요합니다.")
        return actor

    @staticmethod
    def _active_admin_count(connection: _ConnectionAdapter) -> int:
        row = connection.execute(
            """
            SELECT COUNT(*) AS count
            FROM app_users
            WHERE role = 'admin' AND is_active = TRUE
              AND approval_status = 'approved'
            """
        ).fetchone()
        return int(row["count"] if row else 0)

    def has_users(self) -> bool:
        with self._connect() as connection:
            row = connection.execute("SELECT 1 FROM app_users LIMIT 1").fetchone()
        return row is not None

    def create_initial_admin(
        self,
        *,
        username: str,
        display_name: str,
        password: str,
    ) -> AuthUser:
        normalized_username = normalize_username(username)
        normalized_display_name = validate_display_name(display_name)
        password_hash = hash_password(password)
        now = self._serialize_time(self._now())
        with self._lock, self._connect() as connection:
            if self.backend_name == "sqlite":
                connection.execute("BEGIN IMMEDIATE")
            else:
                connection.execute("LOCK TABLE app_users IN EXCLUSIVE MODE")
            if connection.execute("SELECT 1 FROM app_users LIMIT 1").fetchone() is not None:
                raise AuthError("초기 관리자가 이미 설정되어 있습니다.")
            cursor = connection.execute(
                """
                INSERT INTO app_users (
                    username, display_name, password_hash, role, is_active,
                    must_change_password, approval_status, decision_at,
                    decision_by, created_at, updated_at
                ) VALUES (?, ?, ?, 'admin', ?, ?, 'approved', ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    normalized_username,
                    normalized_display_name,
                    password_hash,
                    True,
                    False,
                    now,
                    normalized_username,
                    now,
                    now,
                ),
            )
            self._write_audit(
                connection,
                actor_username=normalized_username,
                action="INITIAL_ADMIN_CREATED",
                target_username=normalized_username,
            )
            inserted = cursor.fetchone()
            if inserted is None:
                raise AuthError("초기 관리자 계정 번호를 확인하지 못했습니다.")
            user_id = int(inserted["id"])
            row = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (user_id,),
            ).fetchone()
        if row is None:
            raise AuthError("초기 관리자 계정을 확인하지 못했습니다.")
        return self._user_from_row(row)

    def get_user(self, user_id: int) -> AuthUser | None:
        with self._connect() as connection:
            row = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(user_id),),
            ).fetchone()
        return self._user_from_row(row) if row is not None else None

    def list_users(self) -> list[AuthUser]:
        with self._connect() as connection:
            rows = connection.execute(
                "SELECT * FROM app_users ORDER BY username"
            ).fetchall()
        return [self._user_from_row(row) for row in rows]

    def authenticate_with_status(
        self,
        username: str,
        password: str,
    ) -> AuthenticationResult:
        try:
            normalized_username = normalize_username(username)
        except AuthError:
            return AuthenticationResult(None, "invalid_credentials")
        now = self._now()
        now_text = self._serialize_time(now)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT * FROM app_users WHERE username = ?",
                (normalized_username,),
            ).fetchone()
            if row is None:
                return AuthenticationResult(None, "invalid_credentials")
            locked_until = self._parse_time(row["locked_until"])
            if locked_until is not None and locked_until > now:
                return AuthenticationResult(None, "locked")
            if not verify_password(password, str(row["password_hash"])):
                failed_attempts = int(row["failed_attempts"]) + 1
                next_locked_until: str | None = None
                if failed_attempts >= MAX_FAILED_ATTEMPTS:
                    next_locked_until = self._serialize_time(
                        now + timedelta(minutes=LOCK_MINUTES)
                    )
                connection.execute(
                    """
                    UPDATE app_users
                    SET failed_attempts = ?, locked_until = ?, updated_at = ?
                    WHERE id = ?
                    """,
                    (failed_attempts, next_locked_until, now_text, int(row["id"])),
                )
                self._write_audit(
                    connection,
                    actor_username=normalized_username,
                    action="LOGIN_FAILED",
                    target_username=normalized_username,
                    detail=("ACCOUNT_LOCKED" if next_locked_until else "INVALID_PASSWORD"),
                )
                return AuthenticationResult(None, "invalid_credentials")
            approval_status = str(row["approval_status"] or "approved")
            if approval_status != "approved":
                self._write_audit(
                    connection,
                    actor_username=normalized_username,
                    action="LOGIN_BLOCKED",
                    target_username=normalized_username,
                    detail=f"approval_status={approval_status}",
                )
                return AuthenticationResult(
                    None,
                    approval_status,
                    (
                        str(row["rejection_reason"])
                        if row["rejection_reason"]
                        else None
                    ),
                )
            if not bool(row["is_active"]):
                return AuthenticationResult(None, "inactive")
            connection.execute(
                """
                UPDATE app_users
                SET failed_attempts = 0, locked_until = NULL,
                    last_login_at = ?, updated_at = ?
                WHERE id = ?
                """,
                (now_text, now_text, int(row["id"])),
            )
            self._write_audit(
                connection,
                actor_username=normalized_username,
                action="LOGIN_SUCCESS",
                target_username=normalized_username,
            )
            updated = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(row["id"]),),
            ).fetchone()
        return AuthenticationResult(
            self._user_from_row(updated) if updated is not None else None,
            "success",
        )

    def authenticate(self, username: str, password: str) -> AuthUser | None:
        return self.authenticate_with_status(username, password).user

    def request_signup(
        self,
        *,
        username: str,
        employee_number: str,
        display_name: str,
        password: str,
    ) -> AuthUser:
        normalized_username = normalize_username(username)
        normalized_employee_number = normalize_employee_number(employee_number)
        normalized_display_name = validate_display_name(display_name)
        password_hash = hash_password(password)
        now = self._serialize_time(self._now())
        with self._lock, self._connect() as connection:
            if connection.execute(
                "SELECT 1 FROM app_users WHERE username = ?",
                (normalized_username,),
            ).fetchone():
                raise AuthError("이미 사용 중이거나 신청된 아이디입니다.")
            if connection.execute(
                "SELECT 1 FROM app_users WHERE employee_number = ?",
                (normalized_employee_number,),
            ).fetchone():
                raise AuthError("이미 등록되거나 신청된 사번입니다.")
            try:
                cursor = connection.execute(
                    """
                    INSERT INTO app_users (
                        username, display_name, password_hash, role,
                        employee_number, approval_status, is_active,
                        must_change_password, signup_requested_at,
                        created_at, updated_at
                    ) VALUES (?, ?, ?, 'user', ?, 'pending', ?, ?, ?, ?, ?)
                    RETURNING id
                    """,
                    (
                        normalized_username,
                        normalized_display_name,
                        password_hash,
                        normalized_employee_number,
                        False,
                        False,
                        now,
                        now,
                        now,
                    ),
                )
            except Exception as exc:
                if self._is_unique_violation(exc):
                    raise AuthError("이미 등록되거나 신청된 아이디 또는 사번입니다.") from exc
                raise
            inserted = cursor.fetchone()
            if inserted is None:
                raise AuthError("회원가입 신청 번호를 확인하지 못했습니다.")
            user_id = int(inserted["id"])
            self._write_audit(
                connection,
                actor_username=normalized_username,
                action="SIGNUP_REQUESTED",
                target_username=normalized_username,
            )
            row = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (user_id,),
            ).fetchone()
        if row is None:
            raise AuthError("회원가입 신청 내역을 확인하지 못했습니다.")
        return self._user_from_row(row)

    def list_signup_requests(
        self,
        *,
        actor_user_id: int,
        status: str = "pending",
    ) -> list[AuthUser]:
        normalized_status = str(status).strip().lower()
        if normalized_status not in VALID_APPROVAL_STATUSES:
            raise AuthError("지원하지 않는 승인 상태입니다.")
        with self._connect() as connection:
            self._require_admin(connection, actor_user_id)
            rows = connection.execute(
                """
                SELECT * FROM app_users
                WHERE approval_status = ?
                ORDER BY signup_requested_at, username
                """,
                (normalized_status,),
            ).fetchall()
        return [self._user_from_row(row) for row in rows]

    def review_signup_request(
        self,
        *,
        actor_user_id: int,
        target_user_id: int,
        approve: bool,
        rejection_reason: str = "",
    ) -> AuthUser:
        normalized_reason = " ".join(str(rejection_reason or "").split())
        if len(normalized_reason) > 500:
            raise AuthError("반려 사유는 500자 이하로 입력하세요.")
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            target = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
            if target is None:
                raise AuthError("회원가입 신청을 찾을 수 없습니다.")
            if str(target["approval_status"]) != "pending":
                raise AuthError("이미 처리된 회원가입 신청입니다.")
            next_status = "approved" if approve else "rejected"
            now = self._serialize_time(self._now())
            connection.execute(
                """
                UPDATE app_users
                SET approval_status = ?, is_active = ?, decision_at = ?,
                    decision_by = ?, rejection_reason = ?,
                    failed_attempts = 0, locked_until = NULL, updated_at = ?
                WHERE id = ?
                """,
                (
                    next_status,
                    bool(approve),
                    now,
                    str(actor["username"]),
                    (None if approve else normalized_reason or None),
                    now,
                    int(target_user_id),
                ),
            )
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action=("SIGNUP_APPROVED" if approve else "SIGNUP_REJECTED"),
                target_username=str(target["username"]),
                detail=("" if approve else normalized_reason),
            )
            updated = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
        if updated is None:
            raise AuthError("처리한 회원가입 신청을 확인하지 못했습니다.")
        return self._user_from_row(updated)

    def create_user(
        self,
        *,
        actor_user_id: int,
        username: str,
        display_name: str,
        temporary_password: str,
        role: str = "user",
    ) -> AuthUser:
        normalized_username = normalize_username(username)
        normalized_display_name = validate_display_name(display_name)
        normalized_role = str(role).strip().lower()
        if normalized_role not in VALID_ROLES:
            raise AuthError("지원하지 않는 권한입니다.")
        password_hash = hash_password(temporary_password)
        now = self._serialize_time(self._now())
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            try:
                cursor = connection.execute(
                    """
                    INSERT INTO app_users (
                        username, display_name, password_hash, role, is_active,
                        must_change_password, approval_status, decision_at,
                        decision_by, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, 'approved', ?, ?, ?, ?)
                    RETURNING id
                    """,
                    (
                        normalized_username,
                        normalized_display_name,
                        password_hash,
                        normalized_role,
                        True,
                        True,
                        now,
                        str(actor["username"]),
                        now,
                        now,
                    ),
                )
            except Exception as exc:
                if self._is_unique_violation(exc):
                    raise AuthError("이미 사용 중인 아이디입니다.") from exc
                raise
            inserted = cursor.fetchone()
            if inserted is None:
                raise AuthError("생성한 계정 번호를 확인하지 못했습니다.")
            user_id = int(inserted["id"])
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action="USER_CREATED",
                target_username=normalized_username,
                detail=f"role={normalized_role}",
            )
            row = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (user_id,),
            ).fetchone()
        if row is None:
            raise AuthError("생성한 계정을 확인하지 못했습니다.")
        return self._user_from_row(row)

    def change_password(
        self,
        *,
        user_id: int,
        current_password: str,
        new_password: str,
    ) -> None:
        validate_password(new_password)
        with self._lock, self._connect() as connection:
            row = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(user_id),),
            ).fetchone()
            if row is None or not bool(row["is_active"]):
                raise AuthError("사용할 수 없는 계정입니다.")
            if not verify_password(current_password, str(row["password_hash"])):
                raise AuthError("현재 비밀번호가 일치하지 않습니다.")
            if verify_password(new_password, str(row["password_hash"])):
                raise PasswordPolicyError("현재 비밀번호와 다른 비밀번호를 입력하세요.")
            now = self._serialize_time(self._now())
            connection.execute(
                """
                UPDATE app_users
                SET password_hash = ?, must_change_password = FALSE,
                    failed_attempts = 0, locked_until = NULL, updated_at = ?
                WHERE id = ?
                """,
                (hash_password(new_password), now, int(user_id)),
            )
            self._write_audit(
                connection,
                actor_username=str(row["username"]),
                action="PASSWORD_CHANGED",
                target_username=str(row["username"]),
            )

    def reset_password(
        self,
        *,
        actor_user_id: int,
        target_user_id: int,
        temporary_password: str,
    ) -> None:
        password_hash = hash_password(temporary_password)
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            target = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
            if target is None:
                raise AuthError("대상 계정을 찾을 수 없습니다.")
            if str(target["approval_status"]) != "approved":
                raise AuthError("승인 완료된 계정만 비밀번호를 초기화할 수 있습니다.")
            now = self._serialize_time(self._now())
            connection.execute(
                """
                UPDATE app_users
                SET password_hash = ?, must_change_password = TRUE,
                    failed_attempts = 0, locked_until = NULL, updated_at = ?
                WHERE id = ?
                """,
                (password_hash, now, int(target_user_id)),
            )
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action="PASSWORD_RESET",
                target_username=str(target["username"]),
            )

    def set_active(
        self,
        *,
        actor_user_id: int,
        target_user_id: int,
        is_active: bool,
    ) -> None:
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            target = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
            if target is None:
                raise AuthError("대상 계정을 찾을 수 없습니다.")
            if is_active and str(target["approval_status"]) != "approved":
                raise AuthError("승인 완료된 계정만 활성화할 수 있습니다.")
            if not is_active and int(target["id"]) == int(actor_user_id):
                raise AuthError("현재 로그인한 관리자 계정은 비활성화할 수 없습니다.")
            if (
                not is_active
                and target["role"] == "admin"
                and bool(target["is_active"])
                and self._active_admin_count(connection) <= 1
            ):
                raise AuthError("마지막 활성 관리자 계정은 비활성화할 수 없습니다.")
            now = self._serialize_time(self._now())
            connection.execute(
                """
                UPDATE app_users
                SET is_active = ?, failed_attempts = 0,
                    locked_until = NULL, updated_at = ?
                WHERE id = ?
                """,
                (bool(is_active), now, int(target_user_id)),
            )
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action=("USER_ACTIVATED" if is_active else "USER_DEACTIVATED"),
                target_username=str(target["username"]),
            )

    def set_role(
        self,
        *,
        actor_user_id: int,
        target_user_id: int,
        role: str,
    ) -> None:
        normalized_role = str(role).strip().lower()
        if normalized_role not in VALID_ROLES:
            raise AuthError("지원하지 않는 권한입니다.")
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            target = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
            if target is None:
                raise AuthError("대상 계정을 찾을 수 없습니다.")
            if str(target["approval_status"]) != "approved":
                raise AuthError("승인 완료된 계정만 권한을 변경할 수 있습니다.")
            if (
                target["role"] == "admin"
                and normalized_role != "admin"
                and bool(target["is_active"])
                and self._active_admin_count(connection) <= 1
            ):
                raise AuthError("마지막 활성 관리자의 권한은 변경할 수 없습니다.")
            now = self._serialize_time(self._now())
            connection.execute(
                "UPDATE app_users SET role = ?, updated_at = ? WHERE id = ?",
                (normalized_role, now, int(target_user_id)),
            )
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action="ROLE_CHANGED",
                target_username=str(target["username"]),
                detail=f"role={normalized_role}",
            )

    def unlock_user(
        self,
        *,
        actor_user_id: int,
        target_user_id: int,
    ) -> None:
        with self._lock, self._connect() as connection:
            actor = self._require_admin(connection, actor_user_id)
            target = connection.execute(
                "SELECT * FROM app_users WHERE id = ?",
                (int(target_user_id),),
            ).fetchone()
            if target is None:
                raise AuthError("대상 계정을 찾을 수 없습니다.")
            if str(target["approval_status"]) != "approved":
                raise AuthError("승인 완료된 계정만 잠금을 해제할 수 있습니다.")
            now = self._serialize_time(self._now())
            connection.execute(
                """
                UPDATE app_users
                SET failed_attempts = 0, locked_until = NULL, updated_at = ?
                WHERE id = ?
                """,
                (now, int(target_user_id)),
            )
            self._write_audit(
                connection,
                actor_username=str(actor["username"]),
                action="USER_UNLOCKED",
                target_username=str(target["username"]),
            )

    def list_audit_events(
        self,
        *,
        actor_user_id: int,
        limit: int = 100,
    ) -> list[AuditEvent]:
        bounded_limit = max(1, min(int(limit), 500))
        with self._connect() as connection:
            self._require_admin(connection, actor_user_id)
            rows = connection.execute(
                """
                SELECT * FROM auth_audit_log
                ORDER BY id DESC
                LIMIT ?
                """,
                (bounded_limit,),
            ).fetchall()
        return [self._audit_from_row(row) for row in rows]

    def import_legacy_sqlite(self, source_path: Path | str) -> MigrationResult:
        source = Path(source_path).resolve()
        if not source.exists():
            raise AuthError(f"이전할 SQLite 계정 DB가 없습니다: {source}")
        if self.path is not None and source == self.path.resolve():
            raise AuthError("원본과 대상 인증 DB가 같습니다.")

        source_uri = f"file:{source.as_posix()}?mode=ro"
        with sqlite3.connect(source_uri, uri=True, timeout=30) as source_connection:
            source_connection.row_factory = sqlite3.Row
            table_names = {
                str(row["name"])
                for row in source_connection.execute(
                    "SELECT name FROM sqlite_master WHERE type = 'table'"
                ).fetchall()
            }
            if "app_users" not in table_names:
                raise AuthError("원본 DB에 app_users 테이블이 없습니다.")
            source_user_columns = {
                str(row["name"])
                for row in source_connection.execute(
                    "PRAGMA table_info(app_users)"
                ).fetchall()
            }
            source_users = source_connection.execute(
                "SELECT * FROM app_users ORDER BY id"
            ).fetchall()
            source_audit_events = (
                source_connection.execute(
                    "SELECT * FROM auth_audit_log ORDER BY id"
                ).fetchall()
                if "auth_audit_log" in table_names
                else []
            )

        if not source_users:
            raise AuthError("원본 DB에 이전할 계정이 없습니다.")
        active_admins = 0
        normalized_users: list[dict[str, Any]] = []
        for row in source_users:
            username = normalize_username(str(row["username"]))
            display_name = validate_display_name(str(row["display_name"]))
            role = str(row["role"])
            if role not in VALID_ROLES:
                raise AuthError(f"지원하지 않는 권한이 있습니다: {username}")
            password_hash = str(row["password_hash"])
            if not password_hash.startswith(f"{PASSWORD_SCHEME}$"):
                raise AuthError(f"지원하지 않는 비밀번호 해시입니다: {username}")
            is_active = bool(row["is_active"])
            approval_status = (
                str(row["approval_status"])
                if "approval_status" in source_user_columns
                else "approved"
            )
            if approval_status not in VALID_APPROVAL_STATUSES:
                raise AuthError(f"지원하지 않는 승인 상태가 있습니다: {username}")
            if role == "admin" and is_active and approval_status == "approved":
                active_admins += 1
            normalized_users.append(
                {
                    "username": username,
                    "display_name": display_name,
                    "password_hash": password_hash,
                    "role": role,
                    "employee_number": (
                        row["employee_number"]
                        if "employee_number" in source_user_columns
                        else None
                    ),
                    "approval_status": approval_status,
                    "is_active": is_active,
                    "must_change_password": bool(row["must_change_password"]),
                    "failed_attempts": int(row["failed_attempts"]),
                    "locked_until": row["locked_until"],
                    "created_at": row["created_at"],
                    "updated_at": row["updated_at"],
                    "last_login_at": row["last_login_at"],
                    "signup_requested_at": (
                        row["signup_requested_at"]
                        if "signup_requested_at" in source_user_columns
                        else None
                    ),
                    "decision_at": (
                        row["decision_at"]
                        if "decision_at" in source_user_columns
                        else None
                    ),
                    "decision_by": (
                        row["decision_by"]
                        if "decision_by" in source_user_columns
                        else None
                    ),
                    "rejection_reason": (
                        row["rejection_reason"]
                        if "rejection_reason" in source_user_columns
                        else None
                    ),
                }
            )
        if active_admins < 1:
            raise AuthError("원본 DB에 활성 관리자 계정이 없습니다.")

        with self._lock, self._connect() as destination:
            if destination.execute("SELECT 1 FROM app_users LIMIT 1").fetchone():
                raise AuthError("대상 인증 DB에 이미 계정이 있어 이전을 중단했습니다.")
            if destination.execute(
                "SELECT 1 FROM auth_audit_log LIMIT 1"
            ).fetchone():
                raise AuthError("대상 인증 DB에 이미 관리 기록이 있어 이전을 중단했습니다.")
            for row in normalized_users:
                destination.execute(
                    """
                    INSERT INTO app_users (
                        username, display_name, password_hash, role,
                        employee_number, approval_status, is_active,
                        must_change_password, failed_attempts, locked_until,
                        created_at, updated_at, last_login_at,
                        signup_requested_at, decision_at, decision_by,
                        rejection_reason
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        row["username"],
                        row["display_name"],
                        row["password_hash"],
                        row["role"],
                        row["employee_number"],
                        row["approval_status"],
                        row["is_active"],
                        row["must_change_password"],
                        row["failed_attempts"],
                        row["locked_until"],
                        row["created_at"],
                        row["updated_at"],
                        row["last_login_at"],
                        row["signup_requested_at"],
                        row["decision_at"],
                        row["decision_by"],
                        row["rejection_reason"],
                    ),
                )
            for row in source_audit_events:
                destination.execute(
                    """
                    INSERT INTO auth_audit_log (
                        actor_username, action, target_username, detail, created_at
                    ) VALUES (?, ?, ?, ?, ?)
                    """,
                    (
                        str(row["actor_username"]),
                        str(row["action"]),
                        str(row["target_username"]),
                        str(row["detail"]),
                        row["created_at"],
                    ),
                )
            self._write_audit(
                destination,
                actor_username="system",
                action="SQLITE_MIGRATION_COMPLETED",
                detail=(
                    f"users={len(normalized_users)},"
                    f"audit_events={len(source_audit_events)}"
                ),
            )
        return MigrationResult(
            users=len(normalized_users),
            audit_events=len(source_audit_events),
        )
